version: '3.8'

services:
  frontend:
    build:
      context: ../..
      dockerfile: config/docker/dev/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../..:/app
      - /app/node_modules
      - /app/packages/frontend/node_modules
    environment:
      - VITE_DIRECTUS_URL=http://localhost:8055
    depends_on:
      - directus

  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    volumes:
      - ../../data/uploads:/directus/uploads
      - ../../data/database:/directus/database
      - ../../data/extensions:/directus/extensions
    env_file:
      - ../env/directus.dev.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

volumes:
  redis_data: